version: "3"

services:
  postgres:
    image: postgres:14.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stocked_food
    ports:
      - "5432:5432"
