name: "Build Repository with Maven"
on:
  workflow_dispatch:
  push:
    branches:
      - main

# @see about pricing https://docs.github.com/ja/billing/managing-billing-for-github-actions/about-billing-for-github-actions#included-storage-and-minutes
jobs:
  build-maven:
    runs-on: ubuntu-latest
    # @see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

# publish GitHub Pages(require public repository)
#      - name: Setup Pages
#        uses: actions/configure-pages@v3
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v2
#        with:
#          path: './target/generated-docs/'
#      # you can access at https://kiyotakeshi.github.io/stocked-food-management/
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v2
