name: "Build Repository with Maven"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # `workflow_dispatch` event では実行したくない場合
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/generated-docs/
          branch: gh-pages
