name: "Build Repository with Maven"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    # @see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './target/generated-docs/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
